// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// FindMLE_CONT_H0_hypergeoC
List FindMLE_CONT_H0_hypergeoC(int n_y0x0z0, int n_y1x0z0, int n_y0x0z1, int n_y1x0z1, int n_y0x1z1, int n_y1x1z1);
RcppExport SEXP noncompliance_FindMLE_CONT_H0_hypergeoC(SEXP n_y0x0z0SEXP, SEXP n_y1x0z0SEXP, SEXP n_y0x0z1SEXP, SEXP n_y1x0z1SEXP, SEXP n_y0x1z1SEXP, SEXP n_y1x1z1SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n_y0x0z0(n_y0x0z0SEXP);
    Rcpp::traits::input_parameter< int >::type n_y1x0z0(n_y1x0z0SEXP);
    Rcpp::traits::input_parameter< int >::type n_y0x0z1(n_y0x0z1SEXP);
    Rcpp::traits::input_parameter< int >::type n_y1x0z1(n_y1x0z1SEXP);
    Rcpp::traits::input_parameter< int >::type n_y0x1z1(n_y0x1z1SEXP);
    Rcpp::traits::input_parameter< int >::type n_y1x1z1(n_y1x1z1SEXP);
    __result = Rcpp::wrap(FindMLE_CONT_H0_hypergeoC(n_y0x0z0, n_y1x0z0, n_y0x0z1, n_y1x0z1, n_y0x1z1, n_y1x1z1));
    return __result;
END_RCPP
}
// FindMLE_CONT_H1_hypergeoC
List FindMLE_CONT_H1_hypergeoC(int n_y0x0z0, int n_y1x0z0, int n_y0x0z1, int n_y1x0z1, int n_y0x1z1, int n_y1x1z1);
RcppExport SEXP noncompliance_FindMLE_CONT_H1_hypergeoC(SEXP n_y0x0z0SEXP, SEXP n_y1x0z0SEXP, SEXP n_y0x0z1SEXP, SEXP n_y1x0z1SEXP, SEXP n_y0x1z1SEXP, SEXP n_y1x1z1SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n_y0x0z0(n_y0x0z0SEXP);
    Rcpp::traits::input_parameter< int >::type n_y1x0z0(n_y1x0z0SEXP);
    Rcpp::traits::input_parameter< int >::type n_y0x0z1(n_y0x0z1SEXP);
    Rcpp::traits::input_parameter< int >::type n_y1x0z1(n_y1x0z1SEXP);
    Rcpp::traits::input_parameter< int >::type n_y0x1z1(n_y0x1z1SEXP);
    Rcpp::traits::input_parameter< int >::type n_y1x1z1(n_y1x1z1SEXP);
    __result = Rcpp::wrap(FindMLE_CONT_H1_hypergeoC(n_y0x0z0, n_y1x0z0, n_y0x0z1, n_y1x0z1, n_y0x1z1, n_y1x1z1));
    return __result;
END_RCPP
}
// AllPossiblyObsH0_CONT_C
List AllPossiblyObsH0_CONT_C(int obs_y0x0z0, int obs_y1x0z0, int obs_y0x0z1, int obs_y1x0z1, int obs_y0x1z1, int obs_y1x1z1);
RcppExport SEXP noncompliance_AllPossiblyObsH0_CONT_C(SEXP obs_y0x0z0SEXP, SEXP obs_y1x0z0SEXP, SEXP obs_y0x0z1SEXP, SEXP obs_y1x0z1SEXP, SEXP obs_y0x1z1SEXP, SEXP obs_y1x1z1SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type obs_y0x0z0(obs_y0x0z0SEXP);
    Rcpp::traits::input_parameter< int >::type obs_y1x0z0(obs_y1x0z0SEXP);
    Rcpp::traits::input_parameter< int >::type obs_y0x0z1(obs_y0x0z1SEXP);
    Rcpp::traits::input_parameter< int >::type obs_y1x0z1(obs_y1x0z1SEXP);
    Rcpp::traits::input_parameter< int >::type obs_y0x1z1(obs_y0x1z1SEXP);
    Rcpp::traits::input_parameter< int >::type obs_y1x1z1(obs_y1x1z1SEXP);
    __result = Rcpp::wrap(AllPossiblyObsH0_CONT_C(obs_y0x0z0, obs_y1x0z0, obs_y0x0z1, obs_y1x0z1, obs_y0x1z1, obs_y1x1z1));
    return __result;
END_RCPP
}
// AllPossiblyObsH0qH1_CONT_C
List AllPossiblyObsH0qH1_CONT_C(int obs_y0x0z0, int obs_y1x0z0, int obs_y0x0z1, int obs_y1x0z1, int obs_y0x1z1, int obs_y1x1z1);
RcppExport SEXP noncompliance_AllPossiblyObsH0qH1_CONT_C(SEXP obs_y0x0z0SEXP, SEXP obs_y1x0z0SEXP, SEXP obs_y0x0z1SEXP, SEXP obs_y1x0z1SEXP, SEXP obs_y0x1z1SEXP, SEXP obs_y1x1z1SEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type obs_y0x0z0(obs_y0x0z0SEXP);
    Rcpp::traits::input_parameter< int >::type obs_y1x0z0(obs_y1x0z0SEXP);
    Rcpp::traits::input_parameter< int >::type obs_y0x0z1(obs_y0x0z1SEXP);
    Rcpp::traits::input_parameter< int >::type obs_y1x0z1(obs_y1x0z1SEXP);
    Rcpp::traits::input_parameter< int >::type obs_y0x1z1(obs_y0x1z1SEXP);
    Rcpp::traits::input_parameter< int >::type obs_y1x1z1(obs_y1x1z1SEXP);
    __result = Rcpp::wrap(AllPossiblyObsH0qH1_CONT_C(obs_y0x0z0, obs_y1x0z0, obs_y0x0z1, obs_y1x0z1, obs_y0x1z1, obs_y1x1z1));
    return __result;
END_RCPP
}
// GetPvalueshypergeoC_allpsi_CONT
NumericMatrix GetPvalueshypergeoC_allpsi_CONT(std::vector<int> n_y0x0z0_H0, std::vector<int> n_y1x0z0_H0, std::vector<int> n_y0x0z1_H0, std::vector<int> n_y1x0z1_H0, std::vector<int> n_y0x1z1_H0, std::vector<int> n_y1x1z1_H0, std::vector<int> n_NTy0_H0, std::vector<int> n_CONR_H0, std::vector<int> n_COAR_H0, std::vector<int> n_NTy1_H0, IntegerMatrix critical_regions);
RcppExport SEXP noncompliance_GetPvalueshypergeoC_allpsi_CONT(SEXP n_y0x0z0_H0SEXP, SEXP n_y1x0z0_H0SEXP, SEXP n_y0x0z1_H0SEXP, SEXP n_y1x0z1_H0SEXP, SEXP n_y0x1z1_H0SEXP, SEXP n_y1x1z1_H0SEXP, SEXP n_NTy0_H0SEXP, SEXP n_CONR_H0SEXP, SEXP n_COAR_H0SEXP, SEXP n_NTy1_H0SEXP, SEXP critical_regionsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< std::vector<int> >::type n_y0x0z0_H0(n_y0x0z0_H0SEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type n_y1x0z0_H0(n_y1x0z0_H0SEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type n_y0x0z1_H0(n_y0x0z1_H0SEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type n_y1x0z1_H0(n_y1x0z1_H0SEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type n_y0x1z1_H0(n_y0x1z1_H0SEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type n_y1x1z1_H0(n_y1x1z1_H0SEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type n_NTy0_H0(n_NTy0_H0SEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type n_CONR_H0(n_CONR_H0SEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type n_COAR_H0(n_COAR_H0SEXP);
    Rcpp::traits::input_parameter< std::vector<int> >::type n_NTy1_H0(n_NTy1_H0SEXP);
    Rcpp::traits::input_parameter< IntegerMatrix >::type critical_regions(critical_regionsSEXP);
    __result = Rcpp::wrap(GetPvalueshypergeoC_allpsi_CONT(n_y0x0z0_H0, n_y1x0z0_H0, n_y0x0z1_H0, n_y1x0z1_H0, n_y0x1z1_H0, n_y1x1z1_H0, n_NTy0_H0, n_CONR_H0, n_COAR_H0, n_NTy1_H0, critical_regions));
    return __result;
END_RCPP
}
